In [167]:
%run efx_charity

loaded efx algorithm


## Example

In [219]:
#n, t, assignments, items, valuations
data = (3,3,
 np.zeros((3,3)),
 np.array([10., 30., 10.]),
 np.array([[4.2, 2., 1],
        [3., 2.5, 0.1],
        [1., 5., 29]]))
run_and_check(draw=True, inputs=data, log=True)

APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
COULD NOT APPLY U0
trying U2 with source: 1
APPLIED U2
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
APPLIED U0
DONE
player 0 assignments: [ 6. 10.  0.]
player 1 assignments: [ 4. 12.  4.]
player 2 assignments: [0. 8. 6.]


(3,
 3,
 array([[ 6., 10.,  0.],
        [ 4., 12.,  4.],
        [ 0.,  8.,  6.]]),
 array([10., 30., 10.]),
 array([[ 4.2,  2. ,  1. ],
        [ 3. ,  2.5,  0.1],
        [ 1. ,  5. , 29. ]]))

## Randomly generate cases

In [246]:
n = 3
t = 2
items = [20, 5]
for i in range(100):
    print(i)
    valuations = np.random.random((n,t))*10
    data = (n,t, np.zeros((n,t)), items, valuations)
    run_and_check(draw=False, inputs=data, log=False)

0
DONE
player 0 assignments: [7. 2.]
player 1 assignments: [7. 1.]
player 2 assignments: [6. 2.]
1
DONE
player 0 assignments: [7. 2.]
player 1 assignments: [7. 1.]
player 2 assignments: [6. 2.]
2
DONE
player 0 assignments: [7. 2.]
player 1 assignments: [7. 1.]
player 2 assignments: [6. 2.]
3
DONE
player 0 assignments: [4. 3.]
player 1 assignments: [8. 1.]
player 2 assignments: [8. 1.]
4
DONE
player 0 assignments: [7. 2.]
player 1 assignments: [7. 1.]
player 2 assignments: [6. 2.]
5
DONE
player 0 assignments: [6. 3.]
player 1 assignments: [7. 1.]
player 2 assignments: [7. 1.]
6
DONE
player 0 assignments: [7. 1.]
player 1 assignments: [7. 1.]
player 2 assignments: [6. 3.]
7
DONE
player 0 assignments: [8. 1.]
player 1 assignments: [5. 3.]
player 2 assignments: [7. 1.]
8
DONE
player 0 assignments: [8. 1.]
player 1 assignments: [4. 3.]
player 2 assignments: [8. 1.]
9
DONE
player 0 assignments: [7. 2.]
player 1 assignments: [7. 1.]
player 2 assignments: [6. 2.]
10
DONE
player 0 assignments: 

AssertionError: ALL ITEMS SHOULD BE ALLOCATED